### ISSUE TITLE
Fix mobile view 

### ISSUE THREAD

**Issue by AmanRaj1608** [iiitv/algos-web#10]
### Adjust text inside computer like web version.

**Web view - >**

![image](https://user-images.githubusercontent.com/42104907/67635800-788f2f80-f8f0-11e9-9eeb-5880373016ca.png)

**Mobile view - >** 

![image](https://user-images.githubusercontent.com/42104907/67635785-5c8b8e00-f8f0-11e9-9950-11fe39db23af.png)

This can be fixed using [CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp)

**Comment by mohitkyadav** [comment]
fixed in #18
