### ISSUE TITLE
Loader is not stopping at landing page.

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [iiitv/algos-web#21]
![Screenshot (99)](https://user-images.githubusercontent.com/56167998/91636978-758a3180-ea22-11ea-819e-bdbb08b50fd9.png)

State is not changing here!

![Screenshot (98)](https://user-images.githubusercontent.com/56167998/91636989-88046b00-ea22-11ea-9c06-a7706c9f78ba.png)

@iiitv/project-maintainers

**Comment by yashshah2820** [comment]
@prathmeshkhandelwal1 will you fix it

**Comment by AmanRaj1608** [comment]
I don't think that's an issue  
It was designed that way 😅 

Do you have any new designs or Ideas?

**Comment by prathmeshkhandelwal1** [comment]
@yashshah2820 i dont have much command on redux..but still i will try it xD.
