### ISSUE TITLE
fetch all algos from iiitv/algos

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/algos-web#23]
- fetch algos from ihttps://github.com/iiitv/algos/
- display algos in a temporary ui

For support take a look at https://github.com/mohitkyadav/algos-ngular
this is built with a very old angular js and it is not maintained anymore. But it still works.

**Comment by prathmeshkhandelwal1** [comment]
@iiitv/project-maintainers I would like to work on this, can you assign me this?

**Comment by mohitkyadav** [comment]
good to go @prathmeshkhandelwal1

**Comment by prathmeshkhandelwal1** [comment]
Sir @mohitkyadav  we have to display algos or link of the algo?(like this)
![Screenshot (101)](https://user-images.githubusercontent.com/56167998/91767364-a83a5280-ebf9-11ea-9479-85a237bae91f.png)

**Comment by prathmeshkhandelwal1** [comment]
Sir @mohitkyadav we have to display algos or link of the algo?(like this)
![Screenshot (102)](https://user-images.githubusercontent.com/56167998/91767876-770e5200-ebfa-11ea-8e19-bafa10551aab.png)

**Comment by prathmeshkhandelwal1** [comment]
Sir @mohitkyadav i fetched all the algos from iiitv/algos and as output i printed the list of names of algos having the links of the code, is this okk, Should i make it a PR.
![Screenshot (103)](https://user-images.githubusercontent.com/56167998/91768538-5d213f00-ebfb-11ea-90d7-eaa8335ce1a3.png)

**Comment by mohitkyadav** [comment]
Yes, you can make a pr

**Comment by prathmeshkhandelwal1** [comment]
Sir i tried many times to convert it into functional component but it is giving many error and also app is crashing many times.
![Screenshot (104)](https://user-images.githubusercontent.com/56167998/91961057-4e847600-ed28-11ea-8f1a-7ed9f8a0c6d5.png)
i created a functional component still it is giving error like you should use hooks in functional component.
Is it okk for this to be class component? (and also i m not good at react-hooks and i never used it in my projetcs)
@mohitkyadav 
@iiitv/project-maintainers
