### ISSUE TITLE
Create a cool looking nav bar on the, and link that to the home page

### ISSUE THREAD

**Issue by mohitkyadav** [iiitv/algos-web#26]

**Comment by nlok5923** [comment]
@iiitv/project-maintainers i would like to work on it but please can you elaborate it a bit.

**Comment by nlok5923** [comment]
@mohitkyadav  sir do i have to create it on homepage.

**Comment by mohitkyadav** [comment]
no it's global, create a sperate component and it will be visible on every route.

**Comment by nlok5923** [comment]
@mohitkyadav  it is mandatory to use uikit framework or else can i write my custom css.
