### ISSUE TITLE
Site does not renders in google chrome browser. 

### ISSUE THREAD

**Issue by nlok5923** [iiitv/algos-web#30]
![Screenshot (1354)](https://user-images.githubusercontent.com/56120084/94108851-e3910100-fdf4-11ea-9dff-0b70bddfe91f.png)

`passing several store enhancers to createStore() is not supported`
@iiitv/project-maintainers sir is this issue valid.

**Comment by AmanRaj1608** [comment]
Yes fix this, 
Currently, it doesn't work on Chromiumm
