### ISSUE TITLE
Want to add dynamic particles at Welcome Page

### ISSUE THREAD

**Issue by marizvi** [iiitv/algos-web#47]
Hello Sir,
Our website somehow looks a little bit static in terms of UI,
I have an idea to make it look more dynamic and impressive for the users, and that is to add some dynamic particles in the background but that too in very limited quantity.

I would be glad if u assign me this issue under contribute-a-thon'21 to work upon.

**Comment by prathmeshkhandelwal1** [comment]
Go ahead @marizvi , provide the Figma link of design first.

**Comment by marizvi** [comment]
sorry sir,
but I didn't understand. Which link do I have to provide you first?
I mean let me generate the pull request and if it doesn't look good then let me know.

**Comment by prathmeshkhandelwal1** [comment]
> sorry sir, but I didn't understand. Which link do I have to provide you first? I mean let me generate the pull request and if it doesn't look good then let me know.

What if you coded everything and design doesn't looks good at the end then your work will go in vein, so you can design it on figma( a  designing tool) and share us the design and if that looks good we will grant you the points. That way you have to work less. But still if you want to code it, then you are good to go.

**Comment by marizvi** [comment]
Ohk sir got it Actually, this is the first time I heard about Figma, so I will try using it but still if I find some difficulty using that software then I think direct coding will be more comfortable for me.
And yes, I will try my best not to disappoint you through my small piece of code.

**Comment by marizvi** [comment]
And one more thing, all this contribution will be under contribute-a-thon'21.

**Comment by prathmeshkhandelwal1** [comment]
> Ohk sir got it Actually, this is the first time I heard about Figma, so I will try using it but still if I find some difficulty using that software then I think direct coding will be more comfortable for me. And yes, I will try my best not to disappoint you through my small piece of code.

There's nothing like disappointment bro, consider this as a learning opportunity.

**Comment by prathmeshkhandelwal1** [comment]
> And one more thing, all this contribution will be under contribute-a-thon'21.

yes

**Comment by shivamm0110** [comment]
@marizvi can you apply the dynamic particle for complete background and sliding text for "IIITV Open Source Welcomes You".

**Comment by marizvi** [comment]
Ok sir, I will definitely do that.
By the way i have applied these particles for the entire background, except
the bottom most section of “HOLA GUYS” I think u want to say that I should
apply it to that section as well , rit?

**Comment by shivamm0110** [comment]
Ok so the dynamic particle is visible in the first section's right part, but it is not highlighted in the rest of the section.
[Your PR's preview](https://deploy-preview-51--algos-web.netlify.app/?utm_source=github&utm_campaign=bot_dp)
You can check its z-index and also keep the opacity low, so it doesn't conceal the page content.

**Comment by marizvi** [comment]
![Screenshot 2021-10-03 181104](https://user-images.githubusercontent.com/76868116/135754168-798ada58-c1c5-4c0e-89b5-7a540f77da25.png)

sir this is the screenshot of the first section, here particles are visible to the entire screen ig.

**Comment by marizvi** [comment]
And this is the section where I still have to add them..
![Screenshot 2021-10-03 181135](https://user-images.githubusercontent.com/76868116/135754268-b2257f04-de08-4d2d-9272-2dd85d303b39.png)

**Comment by marizvi** [comment]
Ok by the way I will modify it again and will let u know.

**Comment by shivamm0110** [comment]
Well that's weird, netlify's deployment preview doesn't look like the ss you attached in both chrome and ff, I will ask @prathmeshkhandelwal1 to look into it, also don't mind adding the particles in the last section since there won't be any colour contrast in that section.

**Comment by marizvi** [comment]
yeah sure sir, I will do that along with adjusting the opacity of them as well.

**Comment by marizvi** [comment]
Sir, please have a look at the newer commit now!

**Comment by prathmeshkhandelwal1** [comment]
> Sir, please have a look at the newer commit now!

Let's continue the conversation on PR itself.

**Comment by marizvi** [comment]
Sir, should I now close this issue or u will do that because it has been already solved now.
