### ISSUE TITLE
Deploy to GH Pages using Travis

### ISSUE THREAD

**Issue by aashutoshrathi** [iiitv/algos-web#5]
Auto-deploy to gh-pages on every push to master.
Using TOKEN with Travis. :wink:

**Comment by yashLadha** [comment]
Also, it would be great if we can integrate this https://github.com/kvld/travisci-telegram as well with coding club telegram channel,

**Comment by aashutoshrathi** [comment]
@yashLadha Sensei You can create a separate issue, I'm on it anyways. 
Thanks

**Comment by yashLadha** [comment]
Maybe any junior batch student can take up this issue.

**Comment by aashutoshrathi** [comment]
@iiitv/batch-of-2021 Anyone interested?

**Comment by nlok5923** [comment]
@aashutoshrathi sir i would like to work on this issue but please can you elaborate it a bit.

**Comment by aashutoshrathi** [comment]
I guess this issue is not valid as Netlify supports this now.
@iiitv/project-maintainers update this one.

**Comment by mohitkyadav** [comment]
we use netlify now, closing this.
