### ISSUE TITLE
make the footer link look like a button

### ISSUE THREAD

**Issue by ShravaniAK** [iiitv/algos-web#70]
<img width="1440" alt="Screenshot 2022-10-11 at 1 53 24 PM" src="https://user-images.githubusercontent.com/97099574/195038048-689d83d4-c568-4f0e-8b45-5bb2a998db96.png">

**Comment by Im-Madhur-Gupta** [comment]
@ShravaniAK Provide some description regarding the issue.

**Comment by ShravaniAK** [comment]
here i wanted to convert the blue link "visit the home page " to a button ui

**Comment by ShravaniAK** [comment]
@Im-Madhur-Gupta should i make it look like a button ?

**Comment by Im-Madhur-Gupta** [comment]
@ShravaniAK thats not required.
