### ISSUE TITLE
Add CI Github Workflow

### ISSUE THREAD

**Issue by Alitindrawan24** [iiitv/algos-web#85]
Adding CI GIthub Workflow will be useful to make every new PR into main branch can be run build and test script successfully
Can I work on this?

**Comment by aryanargupta** [comment]
Yeah we were working on setting it up but there are still some issues with it. I am assigning you on this issue. If you face any difficulties ping any of @iiitv/react-maintainers in this thread.

**Comment by Alitindrawan24** [comment]
Hi, I am already create PR about this issue in #90 Can you check that ? Thank you

**Comment by aryanargupta** [comment]
> Hi, I am already create PR about this issue in #90 Can you check that ? Thank you

Yup sure, will review it

**Comment by aryanargupta** [comment]
Merged!
